version: 0.0
os: linux
files:
  - source: jar/target/HelloWorldApp-1.0-SNAPSHOT.jar
    destination: /var/www/ok/

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
