version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven
      - apt-get install -y maven

  build:
    commands:
      - echo Building the Java application
      - mvn clean package

artifacts:
  files:
    - target/*.jar
