version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Maven and Java are pre-installed."

  build:
    commands:
      - echo "Building the Java application"
      - mvn clean package

artifacts:
  files:
    - target/*.jar
